stages:
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME

build:
  image: docker:stable
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $IMAGE_TAG .
    - docker tag $IMAGE_TAG $IMAGE_TAG-$CI_COMMIT_SHA
    - docker push $IMAGE_TAG

  only:
    - master

.deploy_template: &deploy_definition
   stage: deploy
   image: docker:stable
   only:
     - master


deploy:
  <<: *deploy_definition
  image: docker:stable
  stage: deploy
  environment:
    name: review/$CI_COMMIT_REF_NAME
    on_stop: deploy_stop

  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker-compose stop
    - docker-compose pull
    - docker-compose up -d --force-recreate
  only:
    - master

deploy_stop:
  <<: *deploy_definition
  script:
    - docker-compose rm --force --stop
  when: manual
  environment:
    name: review/$CI_COMMIT_REF_NAME
    action: stop

