stages:
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME

services:
- docker:dind

before_script:
- docker info

build:
  image: docker:stable
  stage: build
  script:
    - echo $BOT_TOKEN > token
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $IMAGE_TAG .
    - docker tag $IMAGE_TAG $IMAGE_TAG-$CI_COMMIT_SHA
    - docker push $IMAGE_TAG

  only:
    - master

deploy:
  image: docker:stable
  stage: deploy
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker run -d --restart on-failure --name IFIBlogBot -v ifibot_db:/db $IMAGE_TAG
  only:
    - master
